// <auto-generated />
using System;
using BTTH.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTTH.Migrations
{
    [DbContext(typeof(BTTHMVCContext))]
    [Migration("20230925093832_ClassStudentSubject3")]
    partial class ClassStudentSubject3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTTH.Models.ClassCourse", b =>
                {
                    b.Property<int>("Clsid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Clsid"));

                    b.Property<string>("ClsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClsOrder")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Clsid");

                    b.ToTable("ClassCourse");
                });

            modelBuilder.Entity("BTTH.Models.STDbio", b =>
                {
                    b.Property<int>("STDbioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STDbioId"));

                    b.Property<DateTime?>("DateEnd")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStart")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExamMark")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Progress")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Sbjid")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Stdid")
                        .HasColumnType("int");

                    b.HasKey("STDbioId");

                    b.HasIndex("Sbjid");

                    b.HasIndex("Stdid");

                    b.ToTable("STDbio");
                });

            modelBuilder.Entity("BTTH.Models.Student", b =>
                {
                    b.Property<int>("Stdid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stdid"));

                    b.Property<int>("Clsid")
                        .HasColumnType("int");

                    b.Property<string>("StdAdr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StdBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("StdImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StdTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stdid");

                    b.HasIndex("Clsid");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("BTTH.Models.SubjectCls", b =>
                {
                    b.Property<int>("Sbjid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sbjid"));

                    b.Property<string>("SbjDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SbjName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SbjOrder")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Sbjid");

                    b.ToTable("SubjectCls");
                });

            modelBuilder.Entity("BTTH.Models.User", b =>
                {
                    b.Property<int>("Usid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usid"));

                    b.Property<string>("UsEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Usid");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BTTH.Models.STDbio", b =>
                {
                    b.HasOne("BTTH.Models.SubjectCls", "SubjectCls")
                        .WithMany("STDbio")
                        .HasForeignKey("Sbjid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTTH.Models.Student", "Students")
                        .WithMany("StudentBio")
                        .HasForeignKey("Stdid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Students");

                    b.Navigation("SubjectCls");
                });

            modelBuilder.Entity("BTTH.Models.Student", b =>
                {
                    b.HasOne("BTTH.Models.ClassCourse", "Classroomid")
                        .WithMany("Students")
                        .HasForeignKey("Clsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroomid");
                });

            modelBuilder.Entity("BTTH.Models.ClassCourse", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("BTTH.Models.Student", b =>
                {
                    b.Navigation("StudentBio");
                });

            modelBuilder.Entity("BTTH.Models.SubjectCls", b =>
                {
                    b.Navigation("STDbio");
                });
#pragma warning restore 612, 618
        }
    }
}
